/**
 * Subscribe to an Antigravity (`agy`) CLI's local language server output
 * stream. Each `agy -p` invocation spins up a Connect+JSON gRPC server on
 * a random localhost port; this module:
 *
 *  1. Discovers the port from the CLI log file emitted at startup.
 *  2. Opens a server-streaming RPC (`StreamAgentStateUpdates`) over
 *     Connect+JSON (5-byte length-prefix envelopes) using native `fetch`.
 *  3. Yields decoded JSON `update` messages as the agent runs.
 *
 * Everything happens on 127.0.0.1 — no upstream traffic is generated by
 * this subscription. The agy CLI is doing its own work; we're just
 * reading the same reactive stream its TUI reads.
 *
 * The schema for `StreamAgentStateUpdates` is not in any public proto, so
 * the response is typed loosely as `AgyStreamUpdate` (a structural
 * snapshot of fields observed in the wild). Add fields as needed.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { setTimeout as delay } from "node:timers/promises";
/** Default location of the agy CLI's per-run log files. */
const DEFAULT_LOG_DIR = path.join(process.env.HOME ?? "/root", ".gemini/antigravity-cli/log");
/**
 * Wait for an `agy` language server to come up and report its port via
 * the latest log file. Resolves with the first endpoint whose `/healthz`
 * returns `status: "ok"`, or rejects on timeout.
 */
export async function discoverAgyLs(opts = {}) {
    const timeoutMs = opts.timeoutMs ?? 30_000;
    const logDir = opts.logDir ?? DEFAULT_LOG_DIR;
    const newerThan = opts.newerThanMs ?? Date.now() - 60_000;
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
        if (opts.signal?.aborted)
            throw new Error("discovery aborted");
        const port = opts.logFile
            ? await readHttpPortFromFile(opts.logFile)
            : await readLatestHttpPort(logDir, newerThan);
        if (port !== undefined) {
            const id = await probeHealthz(port);
            if (id)
                return { port, instanceId: id };
        }
        await delay(300);
    }
    throw new Error(`agy language server did not appear within ${timeoutMs}ms`);
}
/**
 * Wait for `agy` to report the conversation (cascade) id for a run into its
 * private `--log-file`, and return it. Deterministic replacement for scanning
 * the shared `conversations/` dir for the newest new file: the id is read from
 * THIS child's own log, so concurrent agy turns can never bind onto each
 * other's cascade.
 *
 * agy logs the id in two equivalent forms early in a run:
 *   `... Created conversation <uuid>`
 *   `... Print mode: conversation=<uuid>, sending message`
 * Either anchor works; we match whichever appears first.
 */
export async function waitForAgyConversationId(opts) {
    const timeoutMs = opts.timeoutMs ?? 30_000;
    const deadline = Date.now() + timeoutMs;
    // Note the separators differ between the two forms: `Created conversation `
    // has a trailing space, `Print mode: conversation=` an `=`. Match both.
    const re = /(?:Created conversation |Print mode: conversation=)([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/;
    while (Date.now() < deadline) {
        if (opts.signal?.aborted)
            throw new Error("aborted waiting for conversation id");
        try {
            const raw = await fs.readFile(opts.logFile, "utf8");
            const m = re.exec(raw);
            if (m?.[1])
                return m[1];
        }
        catch {
            /* log file not written yet — retry */
        }
        await delay(250);
    }
    throw new Error(`agy did not report a conversation id within ${timeoutMs}ms ` +
        `(is \`agy\` installed and logged in?)`);
}
/**
 * Subscribe to live trajectory updates for a running conversation. The
 * returned iterable closes when the LS terminates (typically when the
 * `agy -p` process exits) or when `signal` aborts.
 *
 * Implementation notes:
 *  - Wire framing is the Connect streaming protocol: each message is a
 *    5-byte envelope (1 byte flags + 4-byte big-endian length) followed
 *    by the JSON payload. Flag=0 is a normal message, flag=2 marks the
 *    server's end-of-stream envelope (and carries any final error).
 *  - We strip flag=2 envelopes from the output stream after surfacing
 *    their error, if any, as a thrown exception.
 */
export async function* subscribeToAgyStream(opts) {
    const url = `http://127.0.0.1:${opts.port}` +
        `/exa.language_server_pb.LanguageServerService/StreamAgentStateUpdates`;
    const payload = new TextEncoder().encode(JSON.stringify({
        conversationId: opts.conversationId,
        subscriberId: opts.subscriberId ?? crypto.randomUUID(),
    }));
    const body = wrapConnectEnvelope(0, payload);
    const resp = await fetch(url, {
        method: "POST",
        headers: { "content-type": "application/connect+json" },
        body,
        signal: opts.signal,
    });
    if (!resp.ok || !resp.body) {
        throw new Error(`agy stream subscribe failed: HTTP ${resp.status} ${resp.statusText}`);
    }
    for await (const env of readConnectEnvelopes(resp.body)) {
        const text = new TextDecoder().decode(env.payload);
        let parsed;
        try {
            parsed = JSON.parse(text);
        }
        catch {
            // Malformed JSON: skip rather than poison the whole stream. The
            // wire format is well-defined enough that this should never happen
            // in practice, but defensive parsing keeps a flaky server from
            // taking the bridge down.
            continue;
        }
        if (env.flag === 2) {
            // End-of-stream envelope. May carry an error payload.
            const obj = parsed;
            if (obj?.error?.message) {
                throw new Error(`agy stream ended with error (${obj.error.code ?? "unknown"}): ${obj.error.message}`);
            }
            return;
        }
        // Normal envelopes wrap the update under `update` (server-streaming RPC).
        const update = parsed.update;
        if (update)
            yield update;
    }
}
/**
 * Connect streaming envelope decoder. Reads chunks from a ReadableStream,
 * reassembles `(flag, payload)` frames, and yields them in order.
 *
 * Frame layout:
 *   byte 0        : flags (bit 0 = compressed, bit 1 = end-of-stream)
 *   bytes 1..4    : payload length, big-endian uint32
 *   bytes 5..N    : payload (JSON for application/connect+json)
 */
async function* readConnectEnvelopes(body) {
    const reader = body.getReader();
    let buf = new Uint8Array(0);
    while (true) {
        const { value, done } = await reader.read();
        if (value && value.length > 0) {
            const next = new Uint8Array(buf.length + value.length);
            next.set(buf, 0);
            next.set(value, buf.length);
            buf = next;
        }
        while (buf.length >= 5) {
            const flag = buf[0];
            const len = ((buf[1] << 24) | (buf[2] << 16) | (buf[3] << 8) | buf[4]) >>> 0;
            if (buf.length < 5 + len)
                break;
            const payload = buf.subarray(5, 5 + len);
            yield { flag, payload };
            buf = buf.subarray(5 + len);
        }
        if (done)
            return;
    }
}
/** Wrap a single payload in a Connect envelope. */
function wrapConnectEnvelope(flag, payload) {
    const out = new Uint8Array(5 + payload.length);
    out[0] = flag & 0xff;
    out[1] = (payload.length >>> 24) & 0xff;
    out[2] = (payload.length >>> 16) & 0xff;
    out[3] = (payload.length >>> 8) & 0xff;
    out[4] = payload.length & 0xff;
    out.set(payload, 5);
    return out;
}
/**
 * Parse the most recent cli-*.log under `logDir` and return the HTTP
 * (non-TLS) Connect port if present. Skips files older than
 * `newerThanMs`.
 */
async function readLatestHttpPort(logDir, newerThanMs) {
    let entries;
    try {
        const names = await fs.readdir(logDir);
        entries = await Promise.all(names
            .filter((n) => n.startsWith("cli-") && n.endsWith(".log"))
            .map(async (n) => {
            const st = await fs.stat(path.join(logDir, n));
            return { name: n, mtimeMs: st.mtimeMs };
        }));
    }
    catch {
        return undefined;
    }
    entries.sort((a, b) => b.mtimeMs - a.mtimeMs);
    for (const e of entries) {
        if (e.mtimeMs < newerThanMs)
            break;
        let raw;
        try {
            raw = await fs.readFile(path.join(logDir, e.name), "utf8");
        }
        catch {
            continue;
        }
        const m = /port at (\d+) for HTTP$/m.exec(raw);
        if (m?.[1])
            return Number(m[1]);
    }
    return undefined;
}
/**
 * Read the HTTP (non-TLS) Connect port from a single, known log file — the
 * private `--log-file` path we passed to our own `agy` spawn. Unlike
 * `readLatestHttpPort`, this never scans a shared directory, so it can't pick
 * up another concurrent turn's server. Returns undefined until the line
 * `... listening on random port at <N> for HTTP` has been written.
 */
async function readHttpPortFromFile(file) {
    let raw;
    try {
        raw = await fs.readFile(file, "utf8");
    }
    catch {
        return undefined;
    }
    const m = /port at (\d+) for HTTP$/m.exec(raw);
    return m?.[1] ? Number(m[1]) : undefined;
}
/** Hit `/healthz` on the candidate port; return `instanceId` if OK. */
async function probeHealthz(port) {
    try {
        const resp = await fetch(`http://127.0.0.1:${port}/healthz`, {
            signal: AbortSignal.timeout(1000),
        });
        if (!resp.ok)
            return undefined;
        const j = (await resp.json());
        if (j.status !== "ok" || !j.instanceId)
            return undefined;
        return j.instanceId;
    }
    catch {
        return undefined;
    }
}
//# sourceMappingURL=agy-stream.js.map