/**
 * Subscribe to an Antigravity (`agy`) CLI's local language server output
 * stream. Each `agy -p` invocation spins up a Connect+JSON gRPC server on
 * a random localhost port; this module:
 *
 *  1. Discovers the port from the CLI log file emitted at startup.
 *  2. Opens a server-streaming RPC (`StreamAgentStateUpdates`) over
 *     Connect+JSON (5-byte length-prefix envelopes) using native `fetch`.
 *  3. Yields decoded JSON `update` messages as the agent runs.
 *
 * Everything happens on 127.0.0.1 — no upstream traffic is generated by
 * this subscription. The agy CLI is doing its own work; we're just
 * reading the same reactive stream its TUI reads.
 *
 * The schema for `StreamAgentStateUpdates` is not in any public proto, so
 * the response is typed loosely as `AgyStreamUpdate` (a structural
 * snapshot of fields observed in the wild). Add fields as needed.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { agyFailure } from "./agy-lifecycle.js";
import { ProbeError, redactProbeText } from "./probe-process.js";

/** Explicit subscription rejection, not corrupt frames or a broken active stream. */
export class AgyStreamUnavailableError extends ProbeError {
  readonly streamCode: string;
  readonly streamMessage: string;
  get permitsStdoutFallback(): boolean {
    // Refuse provider/application failures (quota, cancellation, etc.) as
    // failures of this turn; only subscription auth/protocol loses streaming.
    return ["unauthenticated", "permission_denied", "unimplemented", "protocol_error"].includes(this.streamCode)
      || /^http_(?:4\d\d|5\d\d|200)$/.test(this.streamCode);
  }
  constructor(code: string, message: string) {
    const safeCode = redactProbeText(code, process.env).slice(0, 100);
    const safeMessage = redactProbeText(message, process.env).slice(0, 2000);
    super("protocol_error", `AGY stream ${safeCode}: ${safeMessage}`);
    this.streamCode = safeCode;
    this.streamMessage = safeMessage;
  }
}

/** Default location of the agy CLI's per-run log files. */
const DEFAULT_LOG_DIR = path.join(
  process.env.HOME ?? "/root",
  ".gemini/antigravity-cli/log",
);

/** A live LS endpoint we can subscribe to. */
export interface AgyLs {
  /** Plain-HTTP port (Connect+JSON). */
  port: number;
  /** Server-emitted UUID — useful to confirm we're talking to the same process. */
  instanceId: string;
}

/**
 * Wait for an `agy` language server to come up and report its port via
 * the latest log file. Resolves with the first endpoint whose `/healthz`
 * returns `status: "ok"`, or rejects on timeout.
 */
export async function discoverAgyLs(opts: {
  /** Wait up to this many milliseconds before giving up. Default 30s. */
  timeoutMs?: number;
  /**
   * Read the LS port from THIS specific log file (a private `--log-file` path
   * the caller passed to its own `agy` spawn). This is the deterministic,
   * concurrency-safe path: the port comes from our own child's log, so two
   * agy turns running at once can never latch onto each other's language
   * server. Prefer this over `logDir`.
   */
  logFile?: string;
  /**
   * Legacy fallback: scan this directory for `cli-*.log` files and take the
   * newest one's port. Only used when `logFile` is not given. Racy under
   * concurrency (newest-wins can pick another turn's server) — see the
   * `--log-file` fix in agy.ts. Default `~/.gemini/antigravity-cli/log`.
   */
  logDir?: string;
  /** Optional AbortSignal to cancel the discovery loop. */
  signal?: AbortSignal;
  /** Only consider log files modified after this Date (ms epoch). Filters out stale orphans. */
  newerThanMs?: number;
} = {}): Promise<AgyLs> {
  const timeoutMs = opts.timeoutMs ?? 30_000;
  const logDir = opts.logDir ?? DEFAULT_LOG_DIR;
  const newerThan = opts.newerThanMs ?? Date.now() - 60_000;
  const deadline = Date.now() + timeoutMs;

  while (Date.now() < deadline) {
    if (opts.signal?.aborted) throw new Error("discovery aborted");
    const port = opts.logFile
      ? await readHttpPortFromFile(opts.logFile)
      : await readLatestHttpPort(logDir, newerThan);
    if (port !== undefined) {
      const id = await probeHealthz(port, AbortSignal.any([
        ...(opts.signal ? [opts.signal] : []),
        AbortSignal.timeout(Math.max(1, deadline - Date.now())),
      ]));
      if (id) return { port, instanceId: id };
    }
    await delay(Math.min(300, Math.max(1, deadline - Date.now())), undefined, { signal: opts.signal });
  }
  throw new Error(`agy language server did not appear within ${timeoutMs}ms`);
}

/**
 * Wait for `agy` to report the conversation (cascade) id for a run into its
 * private `--log-file`, and return it. Deterministic replacement for scanning
 * the shared `conversations/` dir for the newest new file: the id is read from
 * THIS child's own log, so concurrent agy turns can never bind onto each
 * other's cascade.
 *
 * agy logs the id in two equivalent forms early in a run:
 *   `... Created conversation <uuid>`
 *   `... Print mode: conversation=<uuid>, sending message`
 * Either anchor works; we match whichever appears first.
 */
export async function waitForAgyConversationId(opts: {
  logFile: string;
  /** Wait up to this many milliseconds before giving up. Default 30s. */
  timeoutMs?: number;
  signal?: AbortSignal;
}): Promise<string> {
  const timeoutMs = opts.timeoutMs ?? 30_000;
  const deadline = Date.now() + timeoutMs;
  // Note the separators differ between the two forms: `Created conversation `
  // has a trailing space, `Print mode: conversation=` an `=`. Match both.
  const re =
    /(?:Created conversation |Print mode: conversation=)([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/;
  while (Date.now() < deadline) {
    if (opts.signal?.aborted) throw new Error("aborted waiting for conversation id");
    try {
      const raw = await readAgyLog(opts.logFile);
      const m = re.exec(raw);
      if (m?.[1]) return m[1];
    } catch (error) {
      if (error instanceof Error && error.name === "ProbeError") throw error;
      /* log file not written yet — retry */
    }
    await delay(Math.min(250, Math.max(1, deadline - Date.now())), undefined, { signal: opts.signal });
  }
  throw new Error(
    `agy did not report a conversation id within ${timeoutMs}ms ` +
      `(is \`agy\` installed and logged in?)`,
  );
}

/**
 * One decoded message from the agent state stream. The full proto is not
 * published; this is the subset of fields we've observed. Treat extra
 * fields as opaque — the server may add new ones at any time.
 */
export interface AgyStreamUpdate {
  conversationId?: string;
  trajectoryId?: string;
  status?: string;
  executableStatus?: string;
  executorLoopStatus?: string;
  /** Step deltas live here — see `mainTrajectoryUpdate.stepsUpdate`. */
  mainTrajectoryUpdate?: {
    stepsUpdate?: {
      /** Step indices being updated in this message. */
      indices?: number[];
      /** Parallel array of step payloads. */
      steps?: AgyStep[];
    };
    generatorMetadatasUpdate?: unknown;
    executorMetadatasUpdate?: unknown;
  };
  artifactSnapshotsUpdate?: unknown;
  executorMetadata?: unknown;
  /** Anything else the server sends — pass through to consumers. */
  [k: string]: unknown;
}

/**
 * A single trajectory step. Same step index is re-sent with `status:
 * GENERATING` repeatedly as tokens arrive, then once with `status: DONE`.
 * That's how we get token-level streaming for the final response.
 *
 * The step body lives in a type-specific union field (`plannerResponse`,
 * tool-call sub-messages, etc.) — there is no top-level `content`.
 */
export interface AgyStep {
  /** e.g. CORTEX_STEP_TYPE_USER_INPUT, _PLANNER_RESPONSE, _VIEW_FILE, _RUN_COMMAND, _CHECKPOINT. */
  type?: string;
  /** CORTEX_STEP_STATUS_GENERATING | CORTEX_STEP_STATUS_DONE | _WAITING | _RUNNING | ... */
  status?: string;
  /** Present when `type === "CORTEX_STEP_TYPE_PLANNER_RESPONSE"`. */
  plannerResponse?: {
    /** Visible model text. Grows over multiple GENERATING updates, then final on DONE. */
    modifiedResponse?: string;
    /** Model's chain-of-thought trace. */
    thinking?: string;
    messageId?: string;
    /** e.g. "0.040091584s". */
    thinkingDuration?: string;
    stopReason?: string;
    [k: string]: unknown;
  };
  metadata?: {
    createdAt?: string;
    viewableAt?: string;
    finishedGeneratingAt?: string;
    startedAt?: string;
    completedAt?: string;
    stepGenerationVersion?: number;
    source?: string;
    generatorModel?: string;
    modelUsage?: {
      model?: string;
      inputTokens?: string;
      outputTokens?: string;
      thinkingOutputTokens?: string;
      responseOutputTokens?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /** Tool-call step variants (VIEW_FILE / RUN_COMMAND / ...) carry their payloads in similar union fields. */
  [k: string]: unknown;
}

/**
 * Subscribe to live trajectory updates for a running conversation. The
 * returned iterable closes when the LS terminates (typically when the
 * `agy -p` process exits) or when `signal` aborts.
 *
 * Implementation notes:
 *  - Wire framing is the Connect streaming protocol: each message is a
 *    5-byte envelope (1 byte flags + 4-byte big-endian length) followed
 *    by the JSON payload. Flag=0 is a normal message, flag=2 marks the
 *    server's end-of-stream envelope (and carries any final error).
 *  - We strip flag=2 envelopes from the output stream after surfacing
 *    their error, if any, as a thrown exception.
 */
export async function* subscribeToAgyStream(opts: {
  port: number;
  conversationId: string;
  subscriberId?: string;
  signal?: AbortSignal;
}): AsyncGenerator<AgyStreamUpdate, void, void> {
  const url =
    `http://127.0.0.1:${opts.port}` +
    `/exa.language_server_pb.LanguageServerService/StreamAgentStateUpdates`;
  const payload = new TextEncoder().encode(
    JSON.stringify({
      conversationId: opts.conversationId,
      subscriberId: opts.subscriberId ?? crypto.randomUUID(),
    }),
  );
  const body = wrapConnectEnvelope(0, payload);

  const resp = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/connect+json" },
    body,
    signal: opts.signal,
  });
  if (!resp.ok || !resp.body) {
    await resp.body?.cancel();
    throw new AgyStreamUnavailableError(`http_${resp.status}`, resp.statusText || "subscription has no response body");
  }

  for await (const env of readConnectEnvelopes(resp.body)) {
    const text = new TextDecoder().decode(env.payload);
    let parsed: unknown;
    try {
      parsed = JSON.parse(text);
    } catch {
      // Skipping corrupt frames silently drops native thoughts/results.
      throw agyFailure("protocol_error");
    }
    if (env.flag === 2) {
      // End-of-stream envelope. May carry an error payload.
      const obj = parsed as { error?: { code?: string; message?: string }; code?: string; message?: string };
      const error = obj?.error ?? obj;
      if (typeof error?.code === "string" || typeof error?.message === "string") {
        throw new AgyStreamUnavailableError(
          typeof error.code === "string" ? error.code : "unknown",
          typeof error.message === "string" ? error.message : "subscription rejected",
        );
      }
      return;
    }
    // Normal envelopes wrap the update under `update` (server-streaming RPC).
    const update = (parsed as { update?: AgyStreamUpdate }).update;
    if (update) yield update;
  }
}

/**
 * Connect streaming envelope decoder. Reads chunks from a ReadableStream,
 * reassembles `(flag, payload)` frames, and yields them in order.
 *
 * Frame layout:
 *   byte 0        : flags (bit 0 = compressed, bit 1 = end-of-stream)
 *   bytes 1..4    : payload length, big-endian uint32
 *   bytes 5..N    : payload (JSON for application/connect+json)
 */
async function* readConnectEnvelopes(
  body: ReadableStream<Uint8Array>,
): AsyncGenerator<{ flag: number; payload: Uint8Array }, void, void> {
  const reader = body.getReader();
  const header = new Uint8Array(5);
  let headerBytes = 0;
  let payload: Uint8Array | undefined;
  let payloadBytes = 0;
  let flag = 0;
  // A bogus length prefix must not retain an unbounded stream awaiting a frame.
  const maxFrameBytes = 8 * 1024 * 1024;
  try {
    for (;;) {
      const { value, done } = await reader.read();
      if (done) {
        if (headerBytes) throw agyFailure("protocol_error");
        return;
      }
      // One transport chunk can contain MANY valid frames. Bound the declared
      // frame before allocating it, not the sum of arbitrarily batched frames.
      let offset = 0;
      while (offset < value.length) {
        if (!payload) {
          const take = Math.min(5 - headerBytes, value.length - offset);
          header.set(value.subarray(offset, offset + take), headerBytes);
          headerBytes += take;
          offset += take;
          if (headerBytes < 5) continue;
          flag = header[0]!;
          const len = new DataView(header.buffer).getUint32(1);
          if (len > maxFrameBytes) throw agyFailure("output_overflow");
          if (flag !== 0 && flag !== 2) throw agyFailure("protocol_error");
          payload = new Uint8Array(len);
          payloadBytes = 0;
        }
        const take = Math.min(payload.length - payloadBytes, value.length - offset);
        payload.set(value.subarray(offset, offset + take), payloadBytes);
        payloadBytes += take;
        offset += take;
        if (payloadBytes === payload.length) {
          yield { flag, payload };
          payload = undefined;
          headerBytes = 0;
        }
      }
    }
  } finally {
    // Breaking after IDLE must close the HTTP body before the LS is killed.
    await reader.cancel().catch(() => {});
    reader.releaseLock();
  }
}

/** Wrap a single payload in a Connect envelope. */
function wrapConnectEnvelope(flag: number, payload: Uint8Array): Uint8Array {
  const out = new Uint8Array(5 + payload.length);
  out[0] = flag & 0xff;
  out[1] = (payload.length >>> 24) & 0xff;
  out[2] = (payload.length >>> 16) & 0xff;
  out[3] = (payload.length >>> 8) & 0xff;
  out[4] = payload.length & 0xff;
  out.set(payload, 5);
  return out;
}

/**
 * Parse the most recent cli-*.log under `logDir` and return the HTTP
 * (non-TLS) Connect port if present. Skips files older than
 * `newerThanMs`.
 */
async function readLatestHttpPort(
  logDir: string,
  newerThanMs: number,
): Promise<number | undefined> {
  let entries: Array<{ name: string; mtimeMs: number }>;
  try {
    const names = await fs.readdir(logDir);
    entries = await Promise.all(
      names
        .filter((n) => n.startsWith("cli-") && n.endsWith(".log"))
        .map(async (n) => {
          const st = await fs.stat(path.join(logDir, n));
          return { name: n, mtimeMs: st.mtimeMs };
        }),
    );
  } catch {
    return undefined;
  }
  entries.sort((a, b) => b.mtimeMs - a.mtimeMs);
  for (const e of entries) {
    if (e.mtimeMs < newerThanMs) break;
    let raw: string;
    try {
      raw = await readAgyLog(path.join(logDir, e.name));
    } catch (error) {
      if (error instanceof Error && error.name === "ProbeError") throw error;
      continue;
    }
    const m = /port at (\d+) for HTTP$/m.exec(raw);
    if (m?.[1]) return Number(m[1]);
  }
  return undefined;
}

/**
 * Read the HTTP (non-TLS) Connect port from a single, known log file — the
 * private `--log-file` path we passed to our own `agy` spawn. Unlike
 * `readLatestHttpPort`, this never scans a shared directory, so it can't pick
 * up another concurrent turn's server. Returns undefined until the line
 * `... listening on random port at <N> for HTTP` has been written.
 */
async function readHttpPortFromFile(file: string): Promise<number | undefined> {
  let raw: string;
  try {
    raw = await readAgyLog(file);
  } catch (error) {
    if (error instanceof Error && error.name === "ProbeError") throw error;
    return undefined;
  }
  const m = /port at (\d+) for HTTP$/m.exec(raw);
  return m?.[1] ? Number(m[1]) : undefined;
}

/** Hit `/healthz` on the candidate port; return `instanceId` if OK. */
async function probeHealthz(port: number, signal: AbortSignal): Promise<string | undefined> {
  try {
    const resp = await fetch(`http://127.0.0.1:${port}/healthz`, {
      signal: AbortSignal.any([signal, AbortSignal.timeout(1000)]),
    });
    if (!resp.ok) { await resp.body?.cancel(); return undefined; }
    const j = (await readAgyJsonResponse(resp)) as { status?: string; instanceId?: string };
    if (j.status !== "ok" || !j.instanceId) return undefined;
    return j.instanceId;
  } catch {
    return undefined;
  }
}

/** Bound untrusted log/HTTP input before materializing strings or JSON. */
const AGY_METADATA_BYTES = 8 * 1024 * 1024;
async function readAgyLog(file: string): Promise<string> {
  const handle = await fs.open(file, "r");
  try {
    const buffer = Buffer.alloc(AGY_METADATA_BYTES + 1);
    const { bytesRead } = await handle.read(buffer, 0, buffer.length, 0);
    if (bytesRead > AGY_METADATA_BYTES) throw agyFailure("output_overflow");
    return buffer.subarray(0, bytesRead).toString("utf8");
  } finally { await handle.close(); }
}

export async function readAgyJsonResponse(response: Response): Promise<unknown> {
  if (!response.body) throw agyFailure("protocol_error");
  const reader = response.body.getReader();
  const chunks: Uint8Array[] = [];
  let bytes = 0;
  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      bytes += value.length;
      if (bytes > AGY_METADATA_BYTES) throw agyFailure("output_overflow");
      chunks.push(value);
    }
    try { return JSON.parse(Buffer.concat(chunks).toString("utf8")); }
    catch { throw agyFailure("protocol_error"); }
  } finally {
    await reader.cancel().catch(() => {});
    reader.releaseLock();
  }
}
