import type { AdapterErrorClassification } from "./error-classification.js";

/** #441: policy-free, serializable recovery decision. Provider English belongs
 * to the adapter (#440), never to this resolver. No clocks, catalog, or I/O. */
export type ErrorFact = "yes" | "no" | "unknown";
export interface ErrorAxes {
  transience: "transient" | "terminal" | "unknown";
  charged: ErrorFact;
  sideEffects: ErrorFact;
  sessionUsable: ErrorFact;
  needsHuman: ErrorFact;
}

/** #448's ordering: as-is, fallback model, reattach, fresh context, human. */
export type RecoveryRung = 1 | 2 | 3 | 4 | 5;
export interface RecoveryOption {
  /** Opaque action identity supplied by the caller; never generated by an LLM. */
  id: string;
  rung: RecoveryRung;
}
export interface ResolutionError extends AdapterErrorClassification {
  /** Observed facts take precedence over rule defaults, including unknown. */
  facts?: Readonly<Partial<ErrorAxes>>;
  /** Already viable recovery actions in this binding (not Cancel/Stop Watching
   * controls). Missing inventory is not invented choice. */
  viableOptions?: readonly RecoveryOption[];
}
type MatchFields = Pick<AdapterErrorClassification,
  "errorKind" | "agentId" | "sourceKind" | "exitCode" | "signal">;
export interface ErrorRule {
  id: string;
  /** Exact structured comparisons only. First matching row wins. */
  when: Readonly<Partial<MatchFields>> & Pick<MatchFields, "errorKind">;
  then: Readonly<ErrorAxes> & {
    startRung: RecoveryRung;
    action: "recover" | "stop";
  };
}
export interface ErrorVerdict extends ErrorAxes {
  errorKind: AdapterErrorClassification["errorKind"];
  agentId: string;
  ruleId: string | null;
  startRung: RecoveryRung;
  action: "recover" | "stop";
  /** Decisions must remain visible even when there are zero viable actions. */
  surface: true;
  options: RecoveryOption[];
  optionCount: number;
  /** 1: act, 2: ask, 3: watch, when action=recover. Explicit stop never arms a
   * watch. Audience policy/presentation belongs to #450. */
  tier: 1 | 2 | 3;
}

const UNKNOWN_AXES: Readonly<ErrorAxes> = Object.freeze({
  transience: "unknown", charged: "unknown", sideEffects: "unknown",
  sessionUsable: "unknown", needsHuman: "unknown",
});

export function resolveError(error: ResolutionError, rules: readonly ErrorRule[]): ErrorVerdict {
  // Unclassified wrappers occurred in the journal with data=null. Refuse only
  // invented certainty: recovery remains available from rung 1 and is surfaced.
  // A data update cannot turn this fallback into silent abandonment (#439).
  const rule = error.errorKind === "unclassified" ? undefined : rules.find((candidate) =>
    Object.entries(candidate.when).every(([key, value]) => error[key as keyof MatchFields] === value));
  const startRung = rule?.then.startRung ?? 1;
  const action = rule?.then.action ?? "recover";
  // The caller computes viability, including isolated-dispatch delivery proof.
  // Sort by ladder order, retaining upstream fallback ranking within each rung.
  // Deduplicate action IDs so duplicate inventory cannot manufacture a choice.
  const seen = new Set<string>();
  const options = action === "stop" ? [] : (error.viableOptions ?? [])
    .filter((option) => option.rung >= startRung)
    .map((option) => ({ ...option }))
    .sort((a, b) => a.rung - b.rung)
    .filter((option) => {
      if (seen.has(option.id)) return false;
      seen.add(option.id);
      return true;
    });
  const axes = { ...UNKNOWN_AXES, ...rule?.then, ...error.facts };
  return {
    transience: axes.transience, charged: axes.charged, sideEffects: axes.sideEffects,
    sessionUsable: axes.sessionUsable, needsHuman: axes.needsHuman,
    errorKind: error.errorKind, agentId: error.agentId, ruleId: rule?.id ?? null,
    startRung, action, surface: true, options, optionCount: options.length,
    tier: options.length === 0 ? 3 : options.length === 1 ? 1 : 2,
  };
}
